//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace automated_classreport.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_Record
    {
        public int ID { get; set; }
        public string sem { get; set; }
        public string subject { get; set; }
        public string course { get; set; }
        public Nullable<int> teach_Id { get; set; }
        public Nullable<decimal> column_1 { get; set; }
        public Nullable<decimal> column_2 { get; set; }
        public Nullable<decimal> column_3 { get; set; }
        public Nullable<decimal> column_4 { get; set; }
        public Nullable<decimal> column_5 { get; set; }
        public Nullable<decimal> column_6 { get; set; }
        public Nullable<decimal> column_7 { get; set; }
        public Nullable<decimal> column_8 { get; set; }
        public Nullable<decimal> column_9 { get; set; }
        public Nullable<decimal> column_10 { get; set; }
        public Nullable<int> stud_Id { get; set; }
        public Nullable<int> high_score_ID { get; set; }
        public string typeof_column { get; set; }
        public string term_exam { get; set; }
        public Nullable<decimal> wgt { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> term_Score { get; set; }
        public Nullable<decimal> term_total_wgt { get; set; }
        public Nullable<decimal> type_total { get; set; }
        public Nullable<decimal> set_Grade { get; set; }
        public string mount { get; set; }
        public Nullable<decimal> trem_wgt { get; set; }
    }
}
