//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace automated_classreport.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int his_Id { get; set; }
        public Nullable<int> teach_id { get; set; }
        public Nullable<int> sem_Id { get; set; }
        public Nullable<System.DateTime> history1 { get; set; }
        public string semName { get; set; }
        public string sem_mean { get; set; }
    }
}
