//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace automated_classreport.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gradingsysEntities : DbContext
    {
        public gradingsysEntities()
            : base("name=gradingsysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<user_account> user_account { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<semester> semesters { get; set; }
        public virtual DbSet<class_Record> class_Record { get; set; }
        public virtual DbSet<high_Score> high_Score { get; set; }
        public virtual DbSet<history> histories { get; set; }
    }
}
