//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace automated_classreport.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int t_Id { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> teach_id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Middlename { get; set; }
        public string subject { get; set; }
        public string course_year { get; set; }
        public Nullable<int> sem_Id { get; set; }
    }
}
